In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os

print(os.listdir('/content/drive/MyDrive'))

['Soumi Saha (1).pdf', 'Classroom', 'IMG_20210212_103438.jpg', 'bts proof cd 3', 'Things to watch after NEET.gdoc', 'IMG20240418105149.jpg', 'IMG_20240418_105445.jpg', 'geeksforgeeks.jpg', 'IMG20240805142651.jpg', 'IMG20240805142653.jpg', 'IMG20240805142730.jpg', 'IMG20240805142738.jpg', 'IMG20240805142720.jpg', 'IMG20240805142706.jpg', 'IMG20240805142747.jpg', 'IMG20240805142754.jpg', 'IMG20240805142802.jpg', 'IMG20240805142808.jpg', 'ESP.pdf', 'nptel.jpg', 'Payment Status.pdf', 'Document(2)(3) (2).pdf', 'Document(2)(3) (1).pdf', 'Document(2)(3).pdf', 'prompt a conversation between two friends about c... (1).gdoc', 'prompt a conversation between two friends about c....gdoc', 'Screenshot_2024-09-21-18-14-46-970_com.android.chrome.jpg', 'Screenshot_2024-09-25-22-22-18-003_com.android.chrome.jpg', 'Blue Geometric Background Poster_20241005_161750_0000.png', 'GX013459.MP4', 'Developing Soft Skills and Personality (1) (1).pdf', 'Developing Soft Skills and Personality (1).pdf', 'library card.jpg', 'DOC-20241209-WA0037..pdf', 'ID.docx', 'Screenshot_2025-01-25-10-26-29-314_com.google.android.apps.nbu.paisa.user.jpg', 'IMG-20250202-WA0039.jpg', 'Screenshot_2025-02-05-15-51-28-197_com.android.chrome.jpg', 'GooglePay_QR (8).png', 'GooglePay_QR (7).png', 'GooglePay_QR (6).png', 'GooglePay_QR (5).png', 'GooglePay_QR (4).png', 'GooglePay_QR (3).png', 'GooglePay_QR (2).png', 'GooglePay_QR (1).png', 'GooglePay_QR.png', 'MODUS OPERANDI[1].docx', 'IMG-20250305-WA0030 (4).jpg', 'IMG-20250305-WA0030 (3).jpg', 'IMG-20250305-WA0030 (2).jpg', 'IMG-20250305-WA0030 (1).jpg', 'IMG-20250305-WA0030.jpg', 'Untitled document.gdoc', 'Untitled document.docx', 'DHUMPAN SASTHER POKKHE KHOTI KAROK.docx', 'DOC-20250221-WA0000..pdf', 'DOC-20250330-WA0000..pdf', 'IMG-20250206-WA0002 (1).jpg', 'IMG-20250206-WA0002.jpg', 'DOC-20250502-WA0053. (1).pdf', 'DOC-20250502-WA0053..pdf', 'inbound3098443960372129694.jpg', '12024002028217.jpg', 'IMG-20250807-WA0019.jpg', 'Screenshot_2025-08-14-21-54-46-009_com.google.android.gm.jpg', 'IMG-20241128-WA0009(1).jpg', 'Coursera LE5WWEUL3HRG_copy.pdf', 'Soumi Saha-1 (1).pdf', 'Certification.pdf', 'Adobe Scan Nov 11, 2025 (1).pdf', 'Screenshot_2025-11-11-15-37-56-550_com.google.android.apps.nbu.paisa.user.jpg', 'Puzzle.gdoc', 'AIML_A_71.pdf', 'h parameter.gdoc', 'advertising management.gdoc', 'IMG-20260101-WA0071.jpg', 'IMG-20260101-WA0116 (1).jpg', 'IMG-20260101-WA0116.jpg', 'IMG-20260101-WA0115.jpg', 'IMG-20250917-WA0008(2).jpg', 'IFC', 'Screenshot_2026-02-04-15-53-30-820_com.android.chrome.jpg', 'Screenshot_2026-02-05-14-26-28-584_com.google.android.apps.nbu.paisa.user.jpg', 'IMG-20250917-WA0008(3).jpg', 'Certificate.pdf', 'SAVE_20260213_225021.jpg', 'Extra- Curricular (A-71).pdf', 'Colab Notebooks', 'Screenshot_2026-03-01-16-30-22-429_com.android.chrome.jpg', 'Screenshot 2026-03-06 at 7.57.11\u202fPM (1).png', 'Screenshot 2026-03-06 at 7.57.11\u202fPM.png', 'Student ID.jpeg', 'DeadlineSnap_TeamIDIL (1).pptx', 'DeadlineSnap_TeamIDIL.pptx', 'https:  forms.g.txt', 'IEEE_SMC_SBC_Synopsis_SoumiSaha.pdf', 'Double Slash.jpeg', 'COA_ASSIGNMENT_SOUMI_SAHA_A-71.pdf', 'Soumi_Saha_12024002028217_Certificate.pdf', 'Soumi_Saha_12024002028217_Resume (1).pdf', 'Soumi_Saha_12024002028217_Resume.pdf', 'Soumi_Saha_12024002028217_XII.pdf', 'Soumi_Saha_12024002028217_Xth_Marksheet.pdf', 'Soumi_Saha_12024002028217_Courses_Certificate.pdf', 'Soumi_Saha_12024002028217_Passport.jpg', 'Soumi_Saha_12024002028217_Sem3.pdf', 'Soumi_Saha_12024002028217_Sem1.pdf', 'Soumi_Saha_12024002028217_Sem2.pdf', 'TODIFY_FINAL_REPORT2 (1).pdf', 'TODIFY_FINAL_REPORT2.pdf.adding', 'TODIFY_FINAL_REPORT2.pdf', 'NOC26MG19S115870044504936626_copy.pdf', 'Soumi Saha.pdf', 'Screenshot 2026-05-27 at 5.03.13\u202fPM.png', 'WEEK-1 WEB DEVELOPMENT ASSIGNMENT', 'Deadline', 'XXXXXXX5853_P_2026.pdf', 'Cloud anomaly detection']

In [ ]:
import os

path = "/content/drive/MyDrive/Cloud anomaly detection/dataset/API_activity_logs"

print(os.listdir(path))

['Request_logs', 'Response_time', 'API_errors']

In [ ]:
request_path = "/content/drive/MyDrive/Cloud anomaly detection/dataset/API_activity_logs/Request_logs"

import os

print(os.listdir(request_path))

['AWS Cloudtrails Dataset from flaws.cloud_dec12_18features.csv', 'web-server-access-logs_10k.log', 'Web Server Access Logs_archive.zip']

In [ ]:
import pandas as pd

df = pd.read_csv(
    "/content/drive/MyDrive/Cloud anomaly detection/dataset/API_activity_logs/Request_logs/AWS Cloudtrails Dataset from flaws.cloud_dec12_18features.csv"
)

In [ ]:
df.head()

,eventID,eventTime,sourceIPAddress,userAgent,eventName,eventSource,awsRegion,eventVersion,userIdentitytype,eventType,userIdentityaccountId,userIdentityprincipalId,userIdentityarn,userIdentityaccessKeyId,userIdentityuserName,errorCode,errorMessage,requestParametersinstanceType
0,3038ebd2-c98a-4c65-9b6e-e22506292313,2017-02,255.253,[S3Console,ListBuckets,s3.amazonaws.com,us-east-1,1.04,Root,AwsApiCall,811596193553.0,811596193553,arn:aws:iam::811596193553:root,Unknown,Unknown,NaN,NoError,NotApplicable
1,22a0d9b1-deea-4d39-827b-2af7050ed3f3,2017-02,255.253,console.amazonaws.com,GetAccountPasswordPolicy,iam.amazonaws.com,us-east-1,1.02,Root,AwsApiCall,811596193553.0,811596193553,arn:aws:iam::811596193553:root,ASIA79EXPHZ8SRL55OOE,Unknown,NoSuchEntityException,The Password Policy with domain name 811596193...,NotApplicable
2,9facf7ca-cb76-4b19-940c-3de6803f7efb,2017-02,255.253,console.amazonaws.com,GetAccountSummary,iam.amazonaws.com,us-east-1,1.02,Root,AwsApiCall,811596193553.0,811596193553,arn:aws:iam::811596193553:root,ASIA79EXPHZ8SRL55OOE,Unknown,NaN,NoError,NotApplicable
3,6596d3b4-7c98-40b1-867d-f317f1dbdc18,2017-02,255.253,console.amazonaws.com,ListAccountAliases,iam.amazonaws.com,us-east-1,1.02,Root,AwsApiCall,811596193553.0,811596193553,arn:aws:iam::811596193553:root,ASIA79EXPHZ8SRL55OOE,Unknown,NaN,NoError,NotApplicable
4,9f9d038c-e5a5-443e-83d5-4cf00941d399,2017-02,255.253,console.amazonaws.com,ListMFADevices,iam.amazonaws.com,us-east-1,1.02,Root,AwsApiCall,811596193553.0,811596193553,arn:aws:iam::811596193553:root,ASIA79EXPHZ8SRL55OOE,Unknown,NaN,NoError,NotApplicable

In [ ]:
df.shape

(1939207, 18)

In [ ]:
df.columns

Index(['eventID', 'eventTime', 'sourceIPAddress', 'userAgent', 'eventName',
       'eventSource', 'awsRegion', 'eventVersion', 'userIdentitytype',
       'eventType', 'userIdentityaccountId', 'userIdentityprincipalId',
       'userIdentityarn', 'userIdentityaccessKeyId', 'userIdentityuserName',
       'errorCode', 'errorMessage', 'requestParametersinstanceType'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1939207 entries, 0 to 1939206
Data columns (total 18 columns):
 #   Column                         Dtype
---  ------                         -----
 0   eventID                        object
 1   eventTime                      object
 2   sourceIPAddress                object
 3   userAgent                      object
 4   eventName                      object
 5   eventSource                    object
 6   awsRegion                      object
 7   eventVersion                   float64
 8   userIdentitytype               object
 9   eventType                      object
 10  userIdentityaccountId          object
 11  userIdentityprincipalId        object
 12  userIdentityarn                object
 13  userIdentityaccessKeyId        object
 14  userIdentityuserName           object
 15  errorCode                      object
 16  errorMessage                   object
 17  requestParametersinstanceType  object
dtypes: float64(1), object(17)
memory usage: 266.3+ MB

In [ ]:
df.isnull().sum()

eventID                               0
eventTime                             0
sourceIPAddress                       0
userAgent                             0
eventName                             0
eventSource                           0
awsRegion                             0
eventVersion                          0
userIdentitytype                      0
eventType                             0
userIdentityaccountId                 0
userIdentityprincipalId               0
userIdentityarn                       0
userIdentityaccessKeyId               0
userIdentityuserName                  0
errorCode                        431493
errorMessage                          0
requestParametersinstanceType         0
dtype: int64

In [ ]:
response_path = "/content/drive/MyDrive/Cloud anomaly detection/dataset/API_activity_logs/Response_time"

import os
print(os.listdir(response_path))

['processed_events_analysis.csv']

In [ ]:
import pandas as pd

df_response = pd.read_csv(
    "/content/drive/MyDrive/Cloud anomaly detection/dataset/API_activity_logs/Response_time/processed_events_analysis.csv"
)

In [ ]:
df_response.head()

,received_at,environment,project,event_count,schema_version,sdk_version,event_type,category,severity,status,...,method,path,status_code,duration_ms,hour,date,day_of_week,month,week,day
0,2026-02-20T13:00:53.883351,production,client-test-app,2,1.0,2.0.0,LOG,APPLICATION,HIGH,FAILURE,...,NaN,NaN,NaN,NaN,13,2026-02-20,Friday,2,8,20
1,2026-02-20T13:00:53.883351,production,client-test-app,2,1.0,2.0.0,INCOMING_REQUEST,APPLICATION,LOW,SUCCESS,...,GET,/log-error,200.0,0.0,13,2026-02-20,Friday,2,8,20
2,2026-02-20T13:04:48.940264,production,client-test-app,3,1.0,2.0.0,LOG,APPLICATION,HIGH,FAILURE,...,NaN,NaN,NaN,NaN,13,2026-02-20,Friday,2,8,20
3,2026-02-20T13:04:48.940264,production,client-test-app,3,1.0,2.0.0,SERVER_ERROR,APPLICATION,LOW,FAILURE,...,NaN,NaN,NaN,NaN,13,2026-02-20,Friday,2,8,20
4,2026-02-20T13:04:48.940264,production,client-test-app,3,1.0,2.0.0,SERVER_ERROR,APPLICATION,LOW,FAILURE,...,NaN,NaN,NaN,NaN,13,2026-02-20,Friday,2,8,20

In [ ]:
df_response.columns

Index(['received_at', 'environment', 'project', 'event_count',
       'schema_version', 'sdk_version', 'event_type', 'category', 'severity',
       'status', 'timestamp', 'hostname', 'os', 'os_version', 'python_version',
       'region', 'app_version', 'instance_id', 'process_id', 'trace_id',
       'message', 'file', 'line', 'logger_name', 'level', 'method', 'path',
       'status_code', 'duration_ms', 'hour', 'date', 'day_of_week', 'month',
       'week', 'day'],
      dtype='object')

In [ ]:
df_response.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1746 entries, 0 to 1745
Data columns (total 35 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   received_at     1746 non-null   object
 1   environment     1746 non-null   object
 2   project         1746 non-null   object
 3   event_count     1746 non-null   int64
 4   schema_version  1746 non-null   float64
 5   sdk_version     1746 non-null   object
 6   event_type      1746 non-null   object
 7   category        1746 non-null   object
 8   severity        1746 non-null   object
 9   status          1746 non-null   object
 10  timestamp       1746 non-null   object
 11  hostname        1746 non-null   object
 12  os              1746 non-null   object
 13  os_version      1746 non-null   int64
 14  python_version  1746 non-null   object
 15  region          1746 non-null   object
 16  app_version     1746 non-null   object
 17  instance_id     1746 non-null   object
 18  process_id      1746 non-null   int64
 19  trace_id        1746 non-null   object
 20  message         69 non-null     object
 21  file            69 non-null     object
 22  line            69 non-null     float64
 23  logger_name     69 non-null     object
 24  level           69 non-null     object
 25  method          544 non-null    object
 26  path            544 non-null    object
 27  status_code     544 non-null    float64
 28  duration_ms     544 non-null    float64
 29  hour            1746 non-null   int64
 30  date            1746 non-null   object
 31  day_of_week     1746 non-null   object
 32  month           1746 non-null   int64
 33  week            1746 non-null   int64
 34  day             1746 non-null   int64
dtypes: float64(4), int64(7), object(24)
memory usage: 477.6+ KB

In [ ]:
df_response.shape

(1746, 35)

In [ ]:
df_response.isnull().sum()

received_at          0
environment          0
project              0
event_count          0
schema_version       0
sdk_version          0
event_type           0
category             0
severity             0
status               0
timestamp            0
hostname             0
os                   0
os_version           0
python_version       0
region               0
app_version          0
instance_id          0
process_id           0
trace_id             0
message           1677
file              1677
line              1677
logger_name       1677
level             1677
method            1202
path              1202
status_code       1202
duration_ms       1202
hour                 0
date                 0
day_of_week          0
month                0
week                 0
day                  0
dtype: int64

In [ ]:
error_path = "/content/drive/MyDrive/Cloud anomaly detection/dataset/API_activity_logs/API_errors"

import os
print(os.listdir(error_path))

['api_error_logs_with_root_causes_220k_rows.csv']

In [ ]:
df_error = pd.read_csv(
    "/content/drive/MyDrive/Cloud anomaly detection/dataset/API_activity_logs/API_errors/api_error_logs_with_root_causes_220k_rows.csv"
)

In [ ]:
df_error.head()

,timestamp,api_name,service_owner,environment,http_method,endpoint,status_code,error_type,root_cause,latency_ms,...,retry_count,is_retry_successful,client_ip,region,container_id,host_id,thread_id,log_level,error_message,resolution_action
0,2024-01-01 00:00:00,inventory-api,team-beta,dev,DELETE,/v1/lljugd,503,Timeout,High latency in network,9403,...,1,True,192.168.97.252,ap-south-1,xuqbiprmtjwu,zjcdzcnlzt,1258,WARN,Internal server error,Refresh token
1,2024-01-01 00:00:05,user-api,team-alpha,staging,DELETE,/v1/mckssy,500,ClientError,Database connection failure,12798,...,2,False,192.168.134.37,us-west-2,tkpvinlsimyz,gcpwfmdubo,8020,INFO,Internal server error,Fix configuration
2,2024-01-01 00:00:10,order-api,team-alpha,prod,DELETE,/v1/ejvxxt,401,AuthError,Schema validation error,1746,...,4,False,192.168.199.184,us-east-1,tocjxcugfqfx,gqalvwpoum,5427,ERROR,Unauthorized access,Restart service
3,2024-01-01 00:00:15,user-api,team-beta,prod,GET,/v1/noqarz,400,RateLimit,Database connection failure,8021,...,0,True,192.168.206.244,eu-central-1,lbgdfttkzuto,namadinzvh,8447,WARN,Bad gateway,Optimize query
4,2024-01-01 00:00:20,user-api,team-gamma,prod,GET,/v1/rcqwsq,401,ClientError,Missing authorization scope,4924,...,0,False,192.168.63.219,us-west-2,oepkhhmcyzlr,nuqorgcfko,8747,WARN,Internal server error,Restart service

In [ ]:
df_error.columns

Index(['timestamp', 'api_name', 'service_owner', 'environment', 'http_method',
       'endpoint', 'status_code', 'error_type', 'root_cause', 'latency_ms',
       'request_size_bytes', 'response_size_bytes', 'retry_count',
       'is_retry_successful', 'client_ip', 'region', 'container_id', 'host_id',
       'thread_id', 'log_level', 'error_message', 'resolution_action'],
      dtype='object')

In [ ]:
df_error.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220000 entries, 0 to 219999
Data columns (total 22 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   timestamp            220000 non-null  object
 1   api_name             220000 non-null  object
 2   service_owner        220000 non-null  object
 3   environment          220000 non-null  object
 4   http_method          220000 non-null  object
 5   endpoint             220000 non-null  object
 6   status_code          220000 non-null  int64
 7   error_type           183229 non-null  object
 8   root_cause           220000 non-null  object
 9   latency_ms           220000 non-null  int64
 10  request_size_bytes   220000 non-null  int64
 11  response_size_bytes  220000 non-null  int64
 12  retry_count          220000 non-null  int64
 13  is_retry_successful  220000 non-null  bool
 14  client_ip            220000 non-null  object
 15  region               220000 non-null  object
 16  container_id         220000 non-null  object
 17  host_id              220000 non-null  object
 18  thread_id            220000 non-null  int64
 19  log_level            220000 non-null  object
 20  error_message        220000 non-null  object
 21  resolution_action    220000 non-null  object
dtypes: bool(1), int64(6), object(15)
memory usage: 35.5+ MB

In [ ]:
df_error.shape

(220000, 22)

In [ ]:
df_error.isnull().sum()

timestamp                  0
api_name                   0
service_owner              0
environment                0
http_method                0
endpoint                   0
status_code                0
error_type             36771
root_cause                 0
latency_ms                 0
request_size_bytes         0
response_size_bytes        0
retry_count                0
is_retry_successful        0
client_ip                  0
region                     0
container_id               0
host_id                    0
thread_id                  0
log_level                  0
error_message              0
resolution_action          0
dtype: int64

In [ ]:
request_df = df.copy()

In [ ]:
response_df = df_response.copy()

In [ ]:
error_df = df_error.copy()

In [ ]:
request_df.head()

,eventID,eventTime,sourceIPAddress,userAgent,eventName,eventSource,awsRegion,eventVersion,userIdentitytype,eventType,userIdentityaccountId,userIdentityprincipalId,userIdentityarn,userIdentityaccessKeyId,userIdentityuserName,errorCode,errorMessage,requestParametersinstanceType
0,3038ebd2-c98a-4c65-9b6e-e22506292313,2017-02,255.253,[S3Console,ListBuckets,s3.amazonaws.com,us-east-1,1.04,Root,AwsApiCall,811596193553.0,811596193553,arn:aws:iam::811596193553:root,Unknown,Unknown,NaN,NoError,NotApplicable
1,22a0d9b1-deea-4d39-827b-2af7050ed3f3,2017-02,255.253,console.amazonaws.com,GetAccountPasswordPolicy,iam.amazonaws.com,us-east-1,1.02,Root,AwsApiCall,811596193553.0,811596193553,arn:aws:iam::811596193553:root,ASIA79EXPHZ8SRL55OOE,Unknown,NoSuchEntityException,The Password Policy with domain name 811596193...,NotApplicable
2,9facf7ca-cb76-4b19-940c-3de6803f7efb,2017-02,255.253,console.amazonaws.com,GetAccountSummary,iam.amazonaws.com,us-east-1,1.02,Root,AwsApiCall,811596193553.0,811596193553,arn:aws:iam::811596193553:root,ASIA79EXPHZ8SRL55OOE,Unknown,NaN,NoError,NotApplicable
3,6596d3b4-7c98-40b1-867d-f317f1dbdc18,2017-02,255.253,console.amazonaws.com,ListAccountAliases,iam.amazonaws.com,us-east-1,1.02,Root,AwsApiCall,811596193553.0,811596193553,arn:aws:iam::811596193553:root,ASIA79EXPHZ8SRL55OOE,Unknown,NaN,NoError,NotApplicable
4,9f9d038c-e5a5-443e-83d5-4cf00941d399,2017-02,255.253,console.amazonaws.com,ListMFADevices,iam.amazonaws.com,us-east-1,1.02,Root,AwsApiCall,811596193553.0,811596193553,arn:aws:iam::811596193553:root,ASIA79EXPHZ8SRL55OOE,Unknown,NaN,NoError,NotApplicable

In [ ]:
response_df.head()

,received_at,environment,project,event_count,schema_version,sdk_version,event_type,category,severity,status,...,method,path,status_code,duration_ms,hour,date,day_of_week,month,week,day
0,2026-02-20T13:00:53.883351,production,client-test-app,2,1.0,2.0.0,LOG,APPLICATION,HIGH,FAILURE,...,NaN,NaN,NaN,NaN,13,2026-02-20,Friday,2,8,20
1,2026-02-20T13:00:53.883351,production,client-test-app,2,1.0,2.0.0,INCOMING_REQUEST,APPLICATION,LOW,SUCCESS,...,GET,/log-error,200.0,0.0,13,2026-02-20,Friday,2,8,20
2,2026-02-20T13:04:48.940264,production,client-test-app,3,1.0,2.0.0,LOG,APPLICATION,HIGH,FAILURE,...,NaN,NaN,NaN,NaN,13,2026-02-20,Friday,2,8,20
3,2026-02-20T13:04:48.940264,production,client-test-app,3,1.0,2.0.0,SERVER_ERROR,APPLICATION,LOW,FAILURE,...,NaN,NaN,NaN,NaN,13,2026-02-20,Friday,2,8,20
4,2026-02-20T13:04:48.940264,production,client-test-app,3,1.0,2.0.0,SERVER_ERROR,APPLICATION,LOW,FAILURE,...,NaN,NaN,NaN,NaN,13,2026-02-20,Friday,2,8,20

In [ ]:
error_df.head()

,timestamp,api_name,service_owner,environment,http_method,endpoint,status_code,error_type,root_cause,latency_ms,...,retry_count,is_retry_successful,client_ip,region,container_id,host_id,thread_id,log_level,error_message,resolution_action
0,2024-01-01 00:00:00,inventory-api,team-beta,dev,DELETE,/v1/lljugd,503,Timeout,High latency in network,9403,...,1,True,192.168.97.252,ap-south-1,xuqbiprmtjwu,zjcdzcnlzt,1258,WARN,Internal server error,Refresh token
1,2024-01-01 00:00:05,user-api,team-alpha,staging,DELETE,/v1/mckssy,500,ClientError,Database connection failure,12798,...,2,False,192.168.134.37,us-west-2,tkpvinlsimyz,gcpwfmdubo,8020,INFO,Internal server error,Fix configuration
2,2024-01-01 00:00:10,order-api,team-alpha,prod,DELETE,/v1/ejvxxt,401,AuthError,Schema validation error,1746,...,4,False,192.168.199.184,us-east-1,tocjxcugfqfx,gqalvwpoum,5427,ERROR,Unauthorized access,Restart service
3,2024-01-01 00:00:15,user-api,team-beta,prod,GET,/v1/noqarz,400,RateLimit,Database connection failure,8021,...,0,True,192.168.206.244,eu-central-1,lbgdfttkzuto,namadinzvh,8447,WARN,Bad gateway,Optimize query
4,2024-01-01 00:00:20,user-api,team-gamma,prod,GET,/v1/rcqwsq,401,ClientError,Missing authorization scope,4924,...,0,False,192.168.63.219,us-west-2,oepkhhmcyzlr,nuqorgcfko,8747,WARN,Internal server error,Restart service

In [ ]:
print("Request duplicates:", request_df.duplicated().sum())
print("Response duplicates:", response_df.duplicated().sum())
print("Error duplicates:", error_df.duplicated().sum())

Request duplicates: 713423
Response duplicates: 0
Error duplicates: 0

In [ ]:
request_df = request_df.drop_duplicates()
print(request_df.shape)

(1225784, 18)

In [ ]:
request_df.isnull().sum()

eventID                               0
eventTime                             0
sourceIPAddress                       0
userAgent                             0
eventName                             0
eventSource                           0
awsRegion                             0
eventVersion                          0
userIdentitytype                      0
eventType                             0
userIdentityaccountId                 0
userIdentityprincipalId               0
userIdentityarn                       0
userIdentityaccessKeyId               0
userIdentityuserName                  0
errorCode                        358121
errorMessage                          0
requestParametersinstanceType         0
dtype: int64

In [ ]:
request_df['errorCode'] = request_df['errorCode'].fillna('NoError')

In [ ]:
response_df[['message',
             'file',
             'line',
             'logger_name',
             'level']].isnull().sum()

message        1677
file           1677
line           1677
logger_name    1677
level          1677
dtype: int64

In [ ]:
response_df = response_df.drop(
    columns=[
        'message',
        'file',
        'line',
        'logger_name',
        'level'
    ]
)

In [ ]:
response_df['method'] = response_df['method'].fillna('Unknown')

response_df['path'] = response_df['path'].fillna('Unknown')

response_df['status_code'] = response_df['status_code'].fillna(0)

response_df['duration_ms'] = response_df['duration_ms'].fillna(
    response_df['duration_ms'].median()
)

In [ ]:
error_df.isnull().sum()

timestamp                  0
api_name                   0
service_owner              0
environment                0
http_method                0
endpoint                   0
status_code                0
error_type             36771
root_cause                 0
latency_ms                 0
request_size_bytes         0
response_size_bytes        0
retry_count                0
is_retry_successful        0
client_ip                  0
region                     0
container_id               0
host_id                    0
thread_id                  0
log_level                  0
error_message              0
resolution_action          0
dtype: int64

In [ ]:
error_df['error_type'] = error_df['error_type'].fillna('NoError')

In [ ]:
print(request_df.isnull().sum().sort_values(ascending=False).head())

print(response_df.isnull().sum().sort_values(ascending=False).head())

print(error_df.isnull().sum().sort_values(ascending=False).head())

eventID            0
eventTime          0
sourceIPAddress    0
userAgent          0
eventName          0
dtype: int64
received_at       0
environment       0
project           0
event_count       0
schema_version    0
dtype: int64
timestamp        0
api_name         0
service_owner    0
environment      0
http_method      0
dtype: int64

In [ ]:
request_df['eventTime'] = pd.to_datetime(
    request_df['eventTime']
)

response_df['timestamp'] = pd.to_datetime(
    response_df['timestamp']
)

error_df['timestamp'] = pd.to_datetime(
    error_df['timestamp']
)

In [ ]:
request_df['hour'] = request_df['eventTime'].dt.hour
request_df['dayofweek'] = request_df['eventTime'].dt.dayofweek

response_df['hour'] = response_df['timestamp'].dt.hour
response_df['dayofweek'] = response_df['timestamp'].dt.dayofweek

error_df['hour'] = error_df['timestamp'].dt.hour
error_df['dayofweek'] = error_df['timestamp'].dt.dayofweek

In [ ]:
request_df['is_error'] = (
    request_df['errorCode'] != 'NoError'
).astype(int)

error_df['is_error'] = (
    error_df['status_code'] >= 400
).astype(int)

In [ ]:
request_features = (
    request_df.groupby('sourceIPAddress')
    .agg(
        request_count=('eventID','count'),
        unique_events=('eventName','nunique'),
        unique_services=('eventSource','nunique'),
        error_count=('is_error','sum'),
        active_hours=('hour','nunique')
    )
    .reset_index()
)

request_features.head()

,sourceIPAddress,request_count,unique_events,unique_services,error_count,active_hours
0,0.0,3560,606,112,2699,1
1,0.1,36,5,4,3,1
2,0.101,1,1,1,0,1
3,0.102,48,13,5,7,1
4,0.109,4,4,2,0,1

In [ ]:
response_features = (
    response_df.groupby('instance_id')
    .agg(
        avg_duration=('duration_ms','mean'),
        max_duration=('duration_ms','max'),
        total_events=('event_count','sum'),
        unique_paths=('path','nunique')
    )
    .reset_index()
)

response_features.head()

,instance_id,avg_duration,max_duration,total_events,unique_paths
0,8ed293ae-de5d-458a-a980-ad5fa32eb63d,96.290378,5037.0,12070,9

In [ ]:
error_features = (
    error_df.groupby('client_ip')
    .agg(
        error_count=('is_error','sum'),
        avg_latency=('latency_ms','mean'),
        retry_sum=('retry_count','sum'),
        unique_endpoints=('endpoint','nunique')
    )
    .reset_index()
)

error_features.head()

       client_ip  error_count  avg_latency  retry_sum  unique_endpoints
0    192.168.0.0            4  8415.200000         11                 5
1    192.168.0.1            5  4646.400000          9                 5
2   192.168.0.10            2  8198.666667         12                 3
3  192.168.0.100            3  7413.666667          2                 3
4  192.168.0.101            9  6608.727273         29                11

In [ ]:
print(request_features.shape)
print(response_features.shape)
print(error_features.shape)

(6851, 6)
(1, 5)
(62801, 5)

In [ ]:
request_features.describe()

response_features.describe()

error_features.describe()

        error_count   avg_latency     retry_sum  unique_endpoints
count  62801.000000  62801.000000  62801.000000      62801.000000
mean       2.921530   7515.279604      6.992659          3.503129
std        1.622921   2695.120649      4.397393          1.757503
min        0.000000     11.000000      0.000000          1.000000
25%        2.000000   5801.625000      4.000000          2.000000
50%        3.000000   7520.500000      6.000000          3.000000
75%        4.000000   9259.000000     10.000000          5.000000
max       12.000000  14995.000000     31.000000         13.000000

In [ ]:
print("Unique instance IDs:", response_df['instance_id'].nunique())

response_df['instance_id'].value_counts().head()

Unique instance IDs: 1

instance_id
8ed293ae-de5d-458a-a980-ad5fa32eb63d    1746
Name: count, dtype: int64

In [ ]:
request_features_extra = (
    request_df.groupby('sourceIPAddress')
    .agg(
        unique_users=('userIdentityuserName', 'nunique'),
        unique_regions=('awsRegion', 'nunique'),
        unique_agents=('userAgent', 'nunique')
    )
    .reset_index()
)

In [ ]:
request_features = request_features.merge(
    request_features_extra,
    on='sourceIPAddress',
    how='left'
)

In [ ]:
print(request_features.shape)

(6851, 9)

In [ ]:
request_features.head()

,sourceIPAddress,request_count,unique_events,unique_services,error_count,active_hours,unique_users,unique_regions,unique_agents
0,0.0,3560,606,112,2699,1,3,3,7
1,0.1,36,5,4,3,1,1,2,2
2,0.101,1,1,1,0,1,1,1,1
3,0.102,48,13,5,7,1,2,2,2
4,0.109,4,4,2,0,1,1,2,1

In [ ]:
request_features['error_rate'] = (
    request_features['error_count']
    /
    request_features['request_count']
)

In [ ]:
request_features[['error_count',
                  'request_count',
                  'error_rate']].head()

   error_count  request_count  error_rate
0         2699           3560    0.758146
1            3             36    0.083333
2            0              1    0.000000
3            7             48    0.145833
4            0              4    0.000000

In [ ]:
request_features.isnull().sum()

sourceIPAddress    0
request_count      0
unique_events      0
unique_services    0
error_count        0
active_hours       0
unique_users       0
unique_regions     0
unique_agents      0
error_rate         0
dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
api_features = request_features.copy()

In [ ]:
feature_cols = [
    'request_count',
    'unique_events',
    'unique_services',
    'error_count',
    'active_hours',
    'unique_users',
    'unique_regions',
    'unique_agents',
    'error_rate'
]

In [ ]:
scaler = StandardScaler()

api_features[feature_cols] = scaler.fit_transform(
    api_features[feature_cols]
)

In [ ]:
api_features.head()

,sourceIPAddress,request_count,unique_events,unique_services,error_count,active_hours,unique_users,unique_regions,unique_agents,error_rate
0,0.0,0.399438,17.108667,15.108641,0.308647,0.0,2.421678,0.341116,5.336238,2.119361
1,0.1,-0.016885,-0.078182,0.105260,-0.014836,0.0,-0.565254,-0.060014,0.336297,-0.183077
2,0.101,-0.021019,-0.192570,-0.311501,-0.015196,0.0,-0.565254,-0.461145,-0.663691,-0.467408
3,0.102,-0.015467,0.150595,0.244180,-0.014356,0.0,0.928212,-0.060014,0.336297,0.030171
4,0.109,-0.020665,-0.106779,-0.172581,-0.015196,0.0,-0.565254,-0.060014,-0.663691,-0.467408

In [ ]:
api_features.describe()

,request_count,unique_events,unique_services,error_count,active_hours,unique_users,unique_regions,unique_agents,error_rate
count,6.851000e+03,6.851000e+03,6.851000e+03,6.851000e+03,6851.0,6.851000e+03,6.851000e+03,6.851000e+03,6.851000e+03
mean,3.111412e-18,4.148549e-18,-8.297098e-18,4.148549e-18,0.0,2.489129e-17,4.148549e-18,-9.956518e-17,3.007698e-17
std,1.000073e+00,1.000073e+00,1.000073e+00,1.000073e+00,0.0,1.000073e+00,1.000073e+00,1.000073e+00,1.000073e+00
min,-2.101940e-02,-1.925701e-01,-3.115008e-01,-1.519599e-02,0.0,-5.652545e-01,-4.611454e-01,-6.636909e-01,-4.674078e-01
25%,-2.101940e-02,-1.925701e-01,-3.115008e-01,-1.519599e-02,0.0,-5.652545e-01,-4.611454e-01,-6.636909e-01,-4.674078e-01
50%,-2.078312e-02,-1.639730e-01,-1.725806e-01,-1.519599e-02,0.0,-5.652545e-01,-6.001448e-02,-6.636909e-01,-4.674078e-01
75%,-1.830219e-02,-7.818179e-02,-3.366042e-02,-1.507601e-02,0.0,9.282119e-01,-6.001448e-02,3.362973e-01,-1.830773e-01
max,8.223808e+01,2.305686e+01,2.024869e+01,8.266431e+01,0.0,6.902078e+00,5.956950e+00,2.233604e+01,2.944558e+00

In [ ]:
api_features['active_hours'].value_counts()

active_hours
0.0    6851
Name: count, dtype: int64

In [ ]:
api_features = api_features.drop(
    columns=['active_hours']
)

In [ ]:
api_features.shape

(6851, 9)

In [ ]:
save_path = "/content/drive/MyDrive/Cloud anomaly detection/processed/api_features.csv"

api_features.to_csv(
    save_path,
    index=False
)

print("Saved successfully")

Saved successfully

In [ ]:
auth_features = pd.read_csv(
    "/content/drive/MyDrive/Cloud anomaly detection/processed/auth_features.csv"
)

system_features = pd.read_csv(
    "/content/drive/MyDrive/Cloud anomaly detection/processed/system_features.csv"
)

In [ ]:
print(auth_features.shape)
print(system_features.shape)

print(auth_features.columns.tolist())

print(system_features.columns.tolist())

(50000, 15)
(405894, 14)
['failed_attempts', 'session_duration', 'password_age_days', 'privilege_level', 'threat_level', 'hour', 'day_of_week', 'month', 'is_failed_login', 'mfa_disabled', 'token_expired_flag', 'blocked_flag', 'suspicious_flag', 'is_weekend', 'late_night_login']
['avg_cpu', 'avg_memory', 'max_cpu', 'max_memory', 'sample_cpu', 'assigned_memory', 'page_cache_memory', 'cycles_per_instruction', 'memory_accesses_per_instruction', 'vertical_scaling', 'scheduler', 'priority', 'scheduling_class', 'failed']

In [ ]:
auth_features.head()

,failed_attempts,session_duration,password_age_days,privilege_level,threat_level,hour,day_of_week,month,is_failed_login,mfa_disabled,token_expired_flag,blocked_flag,suspicious_flag,is_weekend,late_night_login
0,1.583179,1.313836,0.149193,1.410506,1.574488,-1.667803,-0.496064,0.143591,1.002363,0.991754,1.00445,-0.575718,1.006783,-0.627044,1.742179
1,0.316306,1.500625,-0.343562,-0.711619,-0.004161,0.068711,-0.997393,1.590558,-0.997643,0.991754,1.00445,-0.575718,1.006783,-0.627044,-0.573994
2,-1.267284,0.025668,1.646411,-0.711619,1.574488,-1.088965,0.005264,-0.724589,-0.997643,0.991754,-0.99557,-0.575718,-0.993263,-0.627044,1.742179
3,0.316306,-1.706730,0.395571,-0.711619,-0.635621,-1.378384,0.506592,-1.303376,-0.997643,0.991754,-0.99557,-0.575718,1.006783,-0.627044,1.742179
4,-0.000412,0.222135,0.310286,-0.004244,1.258758,0.068711,1.007921,-1.303376,-0.997643,0.991754,1.00445,-0.575718,-0.993263,1.594784,-0.573994

In [ ]:
system_features.head()

,avg_cpu,avg_memory,max_cpu,max_memory,sample_cpu,assigned_memory,page_cache_memory,cycles_per_instruction,memory_accesses_per_instruction,vertical_scaling,scheduler,priority,scheduling_class,failed
0,0.004662,5.920410e-03,0.011902,5.935669e-03,0.004349,0.014435,0.000415,1.918681,0.009506,1.0,0.0,200,3,1
1,0.000000,9.536743e-07,0.000000,9.536743e-07,0.000000,0.000000,0.000000,1.918681,0.009506,2.0,0.0,360,2,1
2,0.024200,2.788544e-03,0.060059,2.845764e-03,0.026459,0.010422,0.000235,0.939919,0.001318,2.0,1.0,103,2,0
3,0.047607,3.442383e-02,0.133301,3.466797e-02,0.050842,0.041626,0.000225,1.359102,0.007643,2.0,0.0,200,3,1
4,0.000271,7.629395e-05,0.000415,7.629395e-05,0.000341,0.000272,0.000010,1.918681,0.009506,3.0,0.0,0,2,0

In [ ]:
system_features.describe()

,avg_cpu,avg_memory,max_cpu,max_memory,sample_cpu,assigned_memory,page_cache_memory,cycles_per_instruction,memory_accesses_per_instruction,vertical_scaling,scheduler,priority,scheduling_class,failed
count,405894.000000,405894.000000,405894.000000,405894.000000,405894.000000,405894.000000,405894.000000,405894.000000,405894.000000,405894.000000,405894.000000,405894.000000,405894.000000,405894.000000
mean,0.007446,0.005640,0.025352,0.005892,0.007191,0.008927,0.000398,2.103451,0.010348,1.859074,0.369547,147.913793,1.266870,0.228331
std,0.018567,0.016559,0.052681,0.016538,0.019297,0.024937,0.000550,1.052743,0.006478,0.753907,0.482683,116.656633,1.014087,0.419757
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.252846,0.000125,1.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000200,0.000238,0.000794,0.000282,0.000167,0.000196,0.000008,1.354252,0.006084,1.000000,0.000000,103.000000,0.000000,0.000000
50%,0.001049,0.001282,0.005005,0.001444,0.000701,0.002693,0.000227,1.918681,0.009506,2.000000,0.000000,105.000000,1.000000,0.000000
75%,0.007286,0.004257,0.029724,0.004616,0.007042,0.006683,0.000539,2.672982,0.013702,2.000000,1.000000,200.000000,2.000000,0.000000
max,0.538086,0.223877,1.271484,0.224365,0.644531,0.286133,0.008453,105.275932,0.084292,3.000000,1.000000,450.000000,3.000000,1.000000

In [ ]:
system_features.isnull().sum()

avg_cpu                            0
avg_memory                         0
max_cpu                            0
max_memory                         0
sample_cpu                         0
assigned_memory                    0
page_cache_memory                  0
cycles_per_instruction             0
memory_accesses_per_instruction    0
vertical_scaling                   0
scheduler                          0
priority                           0
scheduling_class                   0
failed                             0
dtype: int64