In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
BASE_PATH = "/content/drive/MyDrive/Cloud anomaly detection/dataset"

In [ ]:
!pip install pandas numpy matplotlib seaborn scikit-learn

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

auth_df = pd.read_csv(
    f"{BASE_PATH}/authentication_logs/Authentication & Authorization Failures Dataset/auth_authz_failures_dataset.csv"
)

auth_df.head()

,timestamp,user_id,username,ip_address,device_type,os_type,browser,location,login_method,success,...,token_expired,session_duration,password_age_days,role,privilege_level,suspicious_activity,threat_level,blocked,error_code,system_component
0,2025-07-23 00:10:24,6a214818-e78e-47fc-a728-226c70b18e37,jonesdanielle,148.6.34.231,Tablet,Windows,Edge,"Lake Robertbury, Bhutan",Password,False,...,True,3167,198,Guest,5,True,10,False,ERR003,API Gateway
1,2025-12-09 12:43:10,6ad7f4f8-3b0b-45c8-b6aa-2cf6a10b2040,michaelsanchez,134.106.53.46,PC,MacOS,Edge,"Jeffersonville, India",MFA,True,...,True,3360,146,Admin,2,True,5,False,NaN,Frontend
2,2025-04-10 04:15:24,ec4aa120-d196-45af-98ca-4a13ec08d354,martinezcrystal,164.233.90.226,PC,Linux,Firefox,"Michaelhaven, French Polynesia",API Key,True,...,False,1836,356,Admin,2,False,10,False,NaN,API Gateway
3,2026-02-13 02:22:46,71041fa0-b11c-4df8-ace3-59a60b13d613,michaelhardin,205.62.126.123,PC,Windows,Chrome,"Port Seth, Gambia",API Key,True,...,False,46,224,Admin,2,True,3,False,NaN,Frontend
4,2025-02-15 12:41:34,130c32b7-28e7-4d6c-99e0-2e17a439550e,vincentjoshua,157.225.10.229,PC,iOS,Safari,"Georgeview, Central African Republic",MFA,True,...,True,2039,215,Guest,3,False,9,False,NaN,Frontend

In [ ]:
auth_df.shape

(50000, 25)

In [ ]:
auth_df.columns

Index(['timestamp', 'user_id', 'username', 'ip_address', 'device_type',
       'os_type', 'browser', 'location', 'login_method', 'success',
       'failure_reason', 'auth_type', 'account_status', 'failed_attempts',
       'mfa_enabled', 'token_expired', 'session_duration', 'password_age_days',
       'role', 'privilege_level', 'suspicious_activity', 'threat_level',
       'blocked', 'error_code', 'system_component'],
      dtype='object')

In [ ]:
auth_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   timestamp            50000 non-null  object
 1   user_id              50000 non-null  object
 2   username             50000 non-null  object
 3   ip_address           50000 non-null  object
 4   device_type          50000 non-null  object
 5   os_type              50000 non-null  object
 6   browser              50000 non-null  object
 7   location             50000 non-null  object
 8   login_method         50000 non-null  object
 9   success              50000 non-null  bool
 10  failure_reason       18636 non-null  object
 11  auth_type            50000 non-null  object
 12  account_status       50000 non-null  object
 13  failed_attempts      50000 non-null  int64
 14  mfa_enabled          50000 non-null  bool
 15  token_expired        50000 non-null  bool
 16  session_duration     50000 non-null  int64
 17  password_age_days    50000 non-null  int64
 18  role                 50000 non-null  object
 19  privilege_level      50000 non-null  int64
 20  suspicious_activity  50000 non-null  bool
 21  threat_level         50000 non-null  int64
 22  blocked              50000 non-null  bool
 23  error_code           19860 non-null  object
 24  system_component     50000 non-null  object
dtypes: bool(5), int64(5), object(15)
memory usage: 7.9+ MB

In [ ]:
auth_df.describe()

,failed_attempts,session_duration,password_age_days,privilege_level,threat_level
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,5.001300,1809.478700,182.255760,3.006000,5.013180
std,3.157413,1033.260406,105.530155,1.413692,3.167296
min,0.000000,30.000000,0.000000,1.000000,0.000000
25%,2.000000,915.000000,91.000000,2.000000,2.000000
50%,5.000000,1806.000000,182.000000,3.000000,5.000000
75%,8.000000,2705.000000,273.000000,4.000000,8.000000
max,10.000000,3600.000000,365.000000,5.000000,10.000000

In [ ]:
auth_df.isnull().sum()

timestamp                  0
user_id                    0
username                   0
ip_address                 0
device_type                0
os_type                    0
browser                    0
location                   0
login_method               0
success                    0
failure_reason         31364
auth_type                  0
account_status             0
failed_attempts            0
mfa_enabled                0
token_expired              0
session_duration           0
password_age_days          0
role                       0
privilege_level            0
suspicious_activity        0
threat_level               0
blocked                    0
error_code             30140
system_component           0
dtype: int64

In [ ]:
auth_df.duplicated().sum()

np.int64(0)

In [ ]:
auth_df = auth_df.drop_duplicates()

In [ ]:
auth_df[['success', 'failure_reason', 'error_code']].head(20)

    success      failure_reason error_code
0     False      Account Locked     ERR003
1      True                 NaN        NaN
2      True                 NaN        NaN
3      True                 NaN        NaN
4      True                 NaN        NaN
5      True                 NaN        NaN
6     False      Account Locked     ERR003
7     False                 NaN     ERR001
8      True                 NaN        NaN
9     False       Token Expired     ERR004
10    False                 NaN     ERR004
11    False       Token Expired     ERR001
12    False       Token Expired     ERR002
13    False                 NaN        NaN
14    False  Password Incorrect     ERR002
15    False      Account Locked     ERR003
16     True                 NaN        NaN
17    False      Account Locked     ERR001
18    False       Token Expired     ERR004
19     True                 NaN        NaN

In [ ]:
auth_df['success'].value_counts()

success
True     25059
False    24941
Name: count, dtype: int64

In [ ]:
auth_df.groupby('success')[['failure_reason','error_code']].apply(
    lambda x: x.isnull().sum()
)

         failure_reason  error_code
success
False              6305        5081
True              25059       25059

In [ ]:
auth_df['failure_reason'] = auth_df['failure_reason'].fillna('Unknown')

In [ ]:
auth_df['error_code'] = auth_df['error_code'].fillna('No_Error')

In [ ]:
auth_df.isnull().sum()

timestamp              0
user_id                0
username               0
ip_address             0
device_type            0
os_type                0
browser                0
location               0
login_method           0
success                0
failure_reason         0
auth_type              0
account_status         0
failed_attempts        0
mfa_enabled            0
token_expired          0
session_duration       0
password_age_days      0
role                   0
privilege_level        0
suspicious_activity    0
threat_level           0
blocked                0
error_code             0
system_component       0
dtype: int64

In [ ]:
for col in auth_df.columns:
    print(col)

timestamp
user_id
username
ip_address
device_type
os_type
browser
location
login_method
success
failure_reason
auth_type
account_status
failed_attempts
mfa_enabled
token_expired
session_duration
password_age_days
role
privilege_level
suspicious_activity
threat_level
blocked
error_code
system_component

In [ ]:
auth_df['timestamp'] = pd.to_datetime(auth_df['timestamp'])

In [ ]:
auth_df['timestamp'].dtype

dtype('<M8[ns]')

In [ ]:
auth_df['hour'] = auth_df['timestamp'].dt.hour

auth_df['day_of_week'] = auth_df['timestamp'].dt.dayofweek

auth_df['month'] = auth_df['timestamp'].dt.month

In [ ]:
auth_df['success'].value_counts()

success
True     25059
False    24941
Name: count, dtype: int64

In [ ]:
auth_df['suspicious_activity'].value_counts()

suspicious_activity
False    25169
True     24831
Name: count, dtype: int64

In [ ]:
auth_df['threat_level'].value_counts()

threat_level
10    4641
0     4594
6     4591
7     4558
5     4553
8     4539
9     4517
2     4516
4     4510
3     4507
1     4474
Name: count, dtype: int64

In [ ]:
auth_df['blocked'].value_counts()

blocked
False    37553
True     12447
Name: count, dtype: int64

In [ ]:
auth_df[['failed_attempts',
         'session_duration',
         'password_age_days',
         'privilege_level',
         'threat_level']].describe()

,failed_attempts,session_duration,password_age_days,privilege_level,threat_level
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,5.001300,1809.478700,182.255760,3.006000,5.013180
std,3.157413,1033.260406,105.530155,1.413692,3.167296
min,0.000000,30.000000,0.000000,1.000000,0.000000
25%,2.000000,915.000000,91.000000,2.000000,2.000000
50%,5.000000,1806.000000,182.000000,3.000000,5.000000
75%,8.000000,2705.000000,273.000000,4.000000,8.000000
max,10.000000,3600.000000,365.000000,5.000000,10.000000

In [ ]:
import os

os.makedirs(
    "/content/drive/MyDrive/Cloud anomaly detection/processed",
    exist_ok=True
)

In [ ]:
auth_df.to_csv(
    "/content/drive/MyDrive/Cloud anomaly detection/processed/auth_clean.csv",
    index=False
)

# Authentication Feature Engineering

In [ ]:
# Failed login indicator
auth_df['is_failed_login'] = (~auth_df['success']).astype(int)

# MFA disabled indicator
auth_df['mfa_disabled'] = (~auth_df['mfa_enabled']).astype(int)

# Token expired indicator
auth_df['token_expired_flag'] = auth_df['token_expired'].astype(int)

# Blocked indicator
auth_df['blocked_flag'] = auth_df['blocked'].astype(int)

# Suspicious activity indicator
auth_df['suspicious_flag'] = auth_df['suspicious_activity'].astype(int)

In [ ]:
# Weekend login
auth_df['is_weekend'] = auth_df['day_of_week'].isin([5, 6]).astype(int)

# Late-night login (midnight to 5 AM)
auth_df['late_night_login'] = (
    (auth_df['hour'] >= 0) &
    (auth_df['hour'] <= 5)
).astype(int)

In [ ]:
auth_df[
[
'is_failed_login',
'mfa_disabled',
'token_expired_flag',
'blocked_flag',
'suspicious_flag',
'is_weekend',
'late_night_login'
]
].head()

,is_failed_login,mfa_disabled,token_expired_flag,blocked_flag,suspicious_flag,is_weekend,late_night_login
0,1,1,1,0,1,0,1
1,0,1,1,0,1,0,0
2,0,1,0,0,0,0,1
3,0,1,0,0,1,0,1
4,0,1,1,0,0,1,0

In [ ]:
auth_features = auth_df[
[
'failed_attempts',
'session_duration',
'password_age_days',
'privilege_level',
'threat_level',

'hour',
'day_of_week',
'month',

'is_failed_login',
'mfa_disabled',
'token_expired_flag',
'blocked_flag',
'suspicious_flag',
'is_weekend',
'late_night_login'
]
]

In [ ]:
auth_features.shape

(50000, 15)

In [ ]:
auth_features.head()

,failed_attempts,session_duration,password_age_days,privilege_level,threat_level,hour,day_of_week,month,is_failed_login,mfa_disabled,token_expired_flag,blocked_flag,suspicious_flag,is_weekend,late_night_login
0,10,3167,198,5,10,0,2,7,1,1,1,0,1,0,1
1,6,3360,146,2,5,12,1,12,0,1,1,0,1,0,0
2,1,1836,356,2,10,4,3,4,0,1,0,0,0,0,1
3,6,46,224,2,3,2,4,2,0,1,0,0,1,0,1
4,5,2039,215,3,9,12,5,2,0,1,1,0,0,1,0

In [ ]:
auth_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   failed_attempts     50000 non-null  int64
 1   session_duration    50000 non-null  int64
 2   password_age_days   50000 non-null  int64
 3   privilege_level     50000 non-null  int64
 4   threat_level        50000 non-null  int64
 5   hour                50000 non-null  int32
 6   day_of_week         50000 non-null  int32
 7   month               50000 non-null  int32
 8   is_failed_login     50000 non-null  int64
 9   mfa_disabled        50000 non-null  int64
 10  token_expired_flag  50000 non-null  int64
 11  blocked_flag        50000 non-null  int64
 12  suspicious_flag     50000 non-null  int64
 13  is_weekend          50000 non-null  int64
 14  late_night_login    50000 non-null  int64
dtypes: int32(3), int64(12)
memory usage: 5.1 MB

In [ ]:
from sklearn.preprocessing import StandardScaler
import joblib

In [ ]:
scaler = StandardScaler()

In [ ]:
auth_scaled = scaler.fit_transform(auth_features)

In [ ]:
import os
import joblib

model_path = "/content/drive/MyDrive/Cloud anomaly detection/models/auth"

os.makedirs(model_path, exist_ok=True)

joblib.dump(
    scaler,
    f"{model_path}/auth_scaler.pkl"
)

print("Authentication scaler saved successfully")

Authentication scaler saved successfully

In [ ]:
loaded_scaler = joblib.load(
    f"{model_path}/auth_scaler.pkl"
)

print(type(loaded_scaler))

print("Scaler verification successful")

<class 'sklearn.preprocessing._data.StandardScaler'>
Scaler verification successful

In [ ]:
import pandas as pd

auth_scaled_df = pd.DataFrame(
    auth_scaled,
    columns=auth_features.columns
)

In [ ]:
auth_scaled_df.head()

,failed_attempts,session_duration,password_age_days,privilege_level,threat_level,hour,day_of_week,month,is_failed_login,mfa_disabled,token_expired_flag,blocked_flag,suspicious_flag,is_weekend,late_night_login
0,1.583179,1.313836,0.149193,1.410506,1.574488,-1.667803,-0.496064,0.143591,1.002363,0.991754,1.00445,-0.575718,1.006783,-0.627044,1.742179
1,0.316306,1.500625,-0.343562,-0.711619,-0.004161,0.068711,-0.997393,1.590558,-0.997643,0.991754,1.00445,-0.575718,1.006783,-0.627044,-0.573994
2,-1.267284,0.025668,1.646411,-0.711619,1.574488,-1.088965,0.005264,-0.724589,-0.997643,0.991754,-0.99557,-0.575718,-0.993263,-0.627044,1.742179
3,0.316306,-1.706730,0.395571,-0.711619,-0.635621,-1.378384,0.506592,-1.303376,-0.997643,0.991754,-0.99557,-0.575718,1.006783,-0.627044,1.742179
4,-0.000412,0.222135,0.310286,-0.004244,1.258758,0.068711,1.007921,-1.303376,-0.997643,0.991754,1.00445,-0.575718,-0.993263,1.594784,-0.573994

In [ ]:
import os

os.makedirs(
    "/content/drive/MyDrive/Cloud anomaly detection/processed",
    exist_ok=True
)

In [ ]:
auth_scaled_df.to_csv(
    "/content/drive/MyDrive/Cloud anomaly detection/processed/auth_features.csv",
    index=False
)